site_name: "MIxS"
#theme:
#  name: readthedocs
#  analytics:
#    gtag: G-2SYBSJVZ23
#docs_dir: target/docs
#site_dir: docs
#nav:
#  - Index: index.md
#site_url: https://cmungall.github.io/mixs-source/
#repo_url: https://github.com/cmungall/mixs-source

#site_name: synbio_schema
theme: readthedocs
repo_url: https://github.com/turbomam/mixs-source
docs_dir: docs_stage/docs
site_dir: docs
